// SPDX-FileCopyrightText: 2026 CERN for the benefit of the SHiP Collaboration
//
// SPDX-License-Identifier: LGPL-3.0-or-later

// spline_tune_test.cpp — standalone check of spline_file_tune
//
// Pure file parsing, no GENIE initialization: writes miniature spline XML
// headers to a temporary directory and checks the tune sniffing that
// make_genie_driver uses to refuse mismatched spline files (a mismatch
// otherwise sends GENIE into silent numerical cross-section recomputation).

#include <unistd.h>

#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

#include "genie_driver_setup.hpp"

namespace {

int failures = 0;

void check(bool ok, std::string const& what) {
  if (ok) {
    std::cout << "  PASS: " << what << '\n';
  } else {
    std::cout << "  FAIL: " << what << '\n';
    ++failures;
  }
}

std::filesystem::path test_dir() {
  auto dir = std::filesystem::temp_directory_path() /
             ("spline_tune_test_" + std::to_string(getpid()));
  std::filesystem::create_directories(dir);
  return dir;
}

void write(std::filesystem::path const& path, std::string const& content) {
  std::ofstream out{path, std::ios::binary};
  out << content;
}

}  // namespace

int main() {
  auto const dir = test_dir();

  // The header layout genie::XSecSplineList::SaveSplineList() writes.
  write(dir / "tuned.xml",
        "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n\n"
        "<!-- generated by genie::XSecSplineList::SaveSplineList() -->\n\n"
        "<genie_xsec_spline_list version=\"3.00\" uselog=\"1\">\n\n"
        "  <genie_tune name=\"G18_02a_02_11b\">\n\n"
        "    <spline name=\"...\" nknots=\"250\">\n");
  check(
      aegir::spline_file_tune((dir / "tuned.xml").string()) == "G18_02a_02_11b",
      "tune name read from a gmkspl-style header");

  write(dir / "untuned.xml",
        "<?xml version=\"1.0\"?>\n<genie_xsec_spline_list version=\"2.00\">\n"
        "  <spline name=\"...\">\n");
  check(aegir::spline_file_tune((dir / "untuned.xml").string()).empty(),
        "empty for a header without a genie_tune tag");

  write(dir / "compressed.xml.gz", std::string("\x1f\x8b") + "binary junk");
  check(aegir::spline_file_tune((dir / "compressed.xml.gz").string()).empty(),
        "empty for gzip-compressed files (not sniffed)");

  check(aegir::spline_file_tune((dir / "missing.xml").string()).empty(),
        "empty for a missing file");

  std::filesystem::remove_all(dir);

  if (failures) {
    std::cout << failures << " check(s) FAILED\n";
    return 1;
  }
  std::cout << "all checks passed\n";
  return 0;
}
